/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.project1;
import javax.swing.*;


/**
 *
 * @author aladi
 */
public class NewJFrame extends javax.swing.JFrame {
    private JDesktopPane desktopPane;
    
    public NewJFrame() {
        initComponents();
        setTitle("CRUD APP - Gestion de Registros");
        setSize(800, 600);
        setResizable(false);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        desktopPane = new JDesktopPane();
        setContentPane(desktopPane);
        
        addHeaderTitle();
        addNavigationButtons();
    }
    
    private void addHeaderTitle(){
        JLabel title = new JLabel("Bienvenidos a la Aplicacion CRUD", SwingConstants.CENTER);
        title.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 24));
        title.setBounds(0, 10, 800, 40);
        desktopPane.add(title);
    }
    
    private void addNavigationButtons(){
        JButton btnCreate = new JButton("Crear");
        JButton btnRead = new JButton("Leer");
        JButton btnUpdate = new JButton("Actualizar");
        JButton btnDelete = new JButton("Eliminar");
        
        //Pocisiono los botones en el panel, ahi ajustale sugun tus necesidades
        btnCreate.setBounds(50, 50, 150, 30);
        btnRead.setBounds(50, 100, 150, 30);
        btnUpdate.setBounds(50, 150, 150, 30);
        btnDelete.setBounds(50, 200, 150, 30);
        
        //Agrego los botones al panel principal
        desktopPane.add(btnCreate);
        desktopPane.add(btnRead);
        desktopPane.add(btnUpdate);
        desktopPane.add(btnDelete);
        
        // Agregar eventos a los botones
        btnCreate.addActionListener(e -> openInternalFrame(new CreateFrame()));
        btnRead.addActionListener(e -> openInternalFrame(new ReadFrame()));
        btnUpdate.addActionListener(e -> openInternalFrame(new UpdateFrame()));
        btnDelete.addActionListener(e -> openInternalFrame(new DeleteFrame()));
    }
    
    private void openInternalFrame(JInternalFrame frame){
        desktopPane.add(frame);
        frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true)); 
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
